# Generated by Django 6.0.6 on 2026-09-27 10:30

import data.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(verbose_name='Описание действия')),
                ('action_type', models.CharField(choices=[('maintenance', 'Работа с оборудованием'), ('create', 'Создание объекта'), ('update', 'Редактирование данных'), ('rule_change', 'Изменение правила ТО'), ('link_change', 'Изменение связей'), ('sync', 'Синхронизация с YouTrack'), ('other', 'Прочее действие')], db_index=True, default='other', max_length=30, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('youtrack_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID записи в YouTrack')),
                ('youtrack_issue_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Задача, где лежит копия')),
                ('maintenance_kind', models.CharField(blank=True, choices=[('planned', 'Плановое обслуживание'), ('unplanned', 'Внеплановое обслуживание / ремонт')], db_index=True, max_length=20, null=True, verbose_name='Вид обслуживания')),
                ('planned_for', models.DateField(blank=True, db_index=True, null=True, verbose_name='Закрытая плановая дата')),
            ],
            options={
                'verbose_name': 'История действия',
                'verbose_name_plural': 'История объектов',
                'db_table': 'action_history',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to=data.models.get_attachment_upload_path, verbose_name='Файл')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Превью (фото)')),
                ('youtrack_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID вложения в YouTrack')),
                ('youtrack_issue_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Задача, где лежит копия')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('youtrack_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID комментария в YouTrack')),
                ('youtrack_issue_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Задача, где лежит копия')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя объекта')),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('youtrack_issue_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID задачи в Youtrack')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего обслуживания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Объект данных',
                'verbose_name_plural': 'Объекты данных',
                'db_table': 'data_object',
            },
        ),
        migrations.CreateModel(
            name='DateUpdateRule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название правила')),
                ('rule', models.JSONField(default=dict, verbose_name='Правило расчета (JSON)')),
            ],
            options={
                'verbose_name': 'Правило обновления даты',
                'verbose_name_plural': 'Правила обновления дат',
                'db_table': 'date_update_rule',
            },
        ),
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('specifications', models.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики модели')),
            ],
            options={
                'verbose_name': 'Модель объекта',
                'verbose_name_plural': 'Модели объектов',
                'db_table': 'object_model',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'db_table': 'object_type',
            },
        ),
        migrations.CreateModel(
            name='YouTrackJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sync', 'Синхронизация задачи'), ('comment', 'Отправка комментария'), ('comment_edit', 'Правка комментария'), ('attachment', 'Загрузка вложения'), ('work_item', 'Списание времени'), ('description', 'Обновление описания'), ('move_note', 'Заметка о переносе')], max_length=30, verbose_name='Что сделать')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Выполнено'), ('failed', 'Не удалось')], default='queued', max_length=20, verbose_name='Состояние')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток сделано')),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Не раньше')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('result', models.TextField(blank=True, default='', verbose_name='Итог')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Задание YouTrack',
                'verbose_name_plural': 'Задания YouTrack',
                'db_table': 'youtrack_job',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTrackObsoleteRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_id', models.CharField(max_length=100, verbose_name='Задача YouTrack')),
                ('youtrack_id', models.CharField(max_length=100, verbose_name='Номер записи в YouTrack')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда помечено')),
            ],
            options={
                'verbose_name': 'Устаревшая запись YouTrack',
                'verbose_name_plural': 'Устаревшие записи YouTrack',
                'db_table': 'youtrack_obsolete_record',
            },
        ),
    ]
