# Generated by Django 6.0.6 on 2026-08-18 08:33

import data.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateUpdateRule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название правила')),
                ('rule', models.JSONField(default=dict, verbose_name='Правило расчета (JSON)')),
            ],
            options={
                'verbose_name': 'Правило обновления даты',
                'verbose_name_plural': 'Правила обновления дат',
                'db_table': 'date_update_rule',
            },
        ),
        migrations.CreateModel(
            name='DependencyType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Тип зависимости')),
            ],
            options={
                'verbose_name': 'Тип зависимости',
                'verbose_name_plural': 'Типы зависимостей',
                'db_table': 'dependency_type',
            },
        ),
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('specifications', models.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики модели')),
            ],
            options={
                'verbose_name': 'Модель объекта',
                'verbose_name_plural': 'Модели объектов',
                'db_table': 'object_model',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'db_table': 'object_type',
            },
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя объекта')),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('youtrack_issue_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID задачи в Youtrack')),
                ('next_maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего обслуживания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_objects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('date_update_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_objects', to='data.dateupdaterule', verbose_name='Правило расчета ТО')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_objects', to='data.objectmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Объект данных',
                'verbose_name_plural': 'Объекты данных',
                'db_table': 'data_object',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('youtrack_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID комментария в YouTrack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.dataobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to=data.models.get_attachment_upload_path, verbose_name='Файл')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Превью (фото)')),
                ('youtrack_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID вложения в YouTrack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='data.comment', verbose_name='Комментарий')),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='data.dataobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.TextField(verbose_name='Описание действия')),
                ('action_type', models.CharField(choices=[('maintenance', 'Работа с оборудованием'), ('create', 'Создание объекта'), ('update', 'Редактирование данных'), ('rule_change', 'Изменение правила ТО'), ('link_change', 'Изменение связей'), ('sync', 'Синхронизация с YouTrack'), ('other', 'Прочее действие')], db_index=True, default='other', max_length=30, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('youtrack_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID записи в YouTrack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='data.dataobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'История действия',
                'verbose_name_plural': 'История объектов',
                'db_table': 'action_history',
            },
        ),
        migrations.AddField(
            model_name='objectmodel',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='data.objecttype', verbose_name='Тип объектов'),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('pk', models.CompositePrimaryKey('main', 'subject', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='data.dependencytype', verbose_name='Тип связи')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='data.dataobject', verbose_name='Главный объект')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_relations', to='data.dataobject', verbose_name='Зависимый объект')),
            ],
            options={
                'verbose_name': 'Связь объектов',
                'verbose_name_plural': 'Связи объектов',
                'db_table': 'relation',
            },
        ),
    ]
