# Generated by Django 6.0.6 on 2026-07-16 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateUpdateRule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название правила')),
                ('rule', models.JSONField(default=dict, verbose_name='Правило расчета (JSON)')),
            ],
            options={
                'verbose_name': 'Правило обновления даты',
                'verbose_name_plural': 'Правила обновления дат',
                'db_table': 'date_update_rule',
            },
        ),
        migrations.AddField(
            model_name='dataobject',
            name='date_update_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_objects', to='data.dateupdaterule', verbose_name='Правило расчета ТО'),
        ),
    ]
