# Generated by Django 6.0.6 on 2026-09-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobject',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_objects', to='data.objectmodel', verbose_name='Модель'),
        ),
    ]
