# Generated by Django 6.0.6 on 2026-09-24 14:21

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='data.comment', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data.dataobject', verbose_name='Родительский объект'),
        ),
        migrations.AddField(
            model_name='comment',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.dataobject', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='data.dataobject', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='data_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='data.dataobject', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='date_update_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_objects', to='data.dateupdaterule', verbose_name='Правило расчета ТО'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_objects', to='data.objectmodel', verbose_name='Модель'),
        ),
        migrations.AddConstraint(
            model_name='objecttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('type')), name='unique_object_type_name', violation_error_message='Тип оборудования с таким названием уже существует.'),
        ),
        migrations.AddField(
            model_name='objectmodel',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='data.objecttype', verbose_name='Тип объектов'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['maintenance_kind', 'planned_for'], name='ah_plan_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('object_type'), name='unique_model_name_per_object_type', violation_error_message='Модель с таким названием уже существует для этого типа оборудования.'),
        ),
    ]
