# Generated by Django 6.0.6 on 2026-09-23 04:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_protect_model_on_delete'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='objectmodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('object_type'), name='unique_model_name_per_object_type', violation_error_message='Модель с таким названием уже существует для этого типа оборудования.'),
        ),
    ]
