# Generated by Django 6.0.6 on 2026-09-25 04:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTrackJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sync', 'Синхронизация задачи'), ('comment', 'Отправка комментария'), ('comment_edit', 'Правка комментария'), ('attachment', 'Загрузка вложения'), ('work_item', 'Списание времени'), ('description', 'Обновление описания')], max_length=30, verbose_name='Что сделать')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('done', 'Выполнено'), ('failed', 'Не удалось')], default='queued', max_length=20, verbose_name='Состояние')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток сделано')),
                ('run_after', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Не раньше')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('result', models.TextField(blank=True, default='', verbose_name='Итог')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtrack_jobs', to='data.dataobject', verbose_name='Объект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtrack_jobs', to=settings.AUTH_USER_MODEL, verbose_name='От чьего имени')),
            ],
            options={
                'verbose_name': 'Задание YouTrack',
                'verbose_name_plural': 'Задания YouTrack',
                'db_table': 'youtrack_job',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'run_after'], name='ytjob_ready_idx'), models.Index(fields=['data_object', 'kind', 'status'], name='ytjob_object_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind__in', ('sync', 'description')), ('status__in', ('queued', 'running'))), fields=('data_object', 'kind'), name='unique_pending_singleton_job')],
            },
        ),
    ]
