# Generated by Django 6.0.6 on 2026-09-23 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_unique_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='maintenance_kind',
            field=models.CharField(blank=True, choices=[('planned', 'Плановое обслуживание'), ('unplanned', 'Внеплановое обслуживание / ремонт')], db_index=True, max_length=20, null=True, verbose_name='Вид обслуживания'),
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='planned_for',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Закрытая плановая дата'),
        ),
        migrations.AddIndex(
            model_name='actionhistory',
            index=models.Index(fields=['maintenance_kind', 'planned_for'], name='ah_plan_event_idx'),
        ),
    ]
