"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

# В production ключ обязателен: молчаливый fallback означал бы, что все
# установки подписывают сессии и токены одним и тем же известным ключом.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key'
    else:
        raise ImproperlyConfigured(
            "Не задан SECRET_KEY. Сгенерируйте ключ и добавьте его в .env:\n"
            "  python -c \"from django.core.management.utils import get_random_secret_key; "
            "print(get_random_secret_key())\""
        )

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
    else:
        raise ImproperlyConfigured(
            "Не задан ALLOWED_HOSTS. Перечислите домены сервиса в .env, например:\n"
            "  ALLOWED_HOSTS=mandev.company.ru,10.0.0.5"
        )

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Настройки за обратным прокси (nginx/traefik терминируют TLS).
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', 'False') == 'True'
if os.getenv('SECURE_PROXY_SSL_HEADER', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Безопасность cookies и транспорта. В разработке по HTTP всё это выключено,
# иначе сессия просто не установится.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # значение читает HTMX-обработчик в base.html
X_FRAME_OPTIONS = 'DENY'

ENABLE_HTTPS = os.getenv('ENABLE_HTTPS', 'False') == 'True'
SESSION_COOKIE_SECURE = ENABLE_HTTPS
CSRF_COOKIE_SECURE = ENABLE_HTTPS
SECURE_SSL_REDIRECT = ENABLE_HTTPS
if ENABLE_HTTPS:
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 30))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

AUTH_USER_MODEL = 'users.User'

SESSION_COOKIE_AGE = 1209600

# Динамическая настройка LDAP (если USE_LDAP=True в .env)
USE_LDAP = os.getenv('USE_LDAP', 'False') == 'True'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

if USE_LDAP:
    try:
        import ldap
        from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
        
        ldap_ca_file = os.getenv('AUTH_LDAP_CA_FILE')
        if ldap_ca_file and os.path.exists(ldap_ca_file):
            ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, ldap_ca_file)
            ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
            ldap.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
            
        AUTHENTICATION_BACKENDS.insert(0, "django_auth_ldap.backend.LDAPBackend")
        
        AUTH_LDAP_SERVER_URI = os.getenv('AUTH_LDAP_SERVER_URI', 'ldap://your.domain.ru')
        AUTH_LDAP_START_TLS = True
        AUTH_LDAP_BIND_DN = os.getenv('AUTH_LDAP_BIND_DN', '')
        AUTH_LDAP_BIND_PASSWORD = os.getenv('AUTH_LDAP_BIND_PASSWORD', '')
        
        user_search_dn = os.getenv('AUTH_LDAP_USER_SEARCH_DN', 'cn=users,cn=accounts,dc=your,dc=domain,dc=ru')
        AUTH_LDAP_USER_SEARCH = LDAPSearch(user_search_dn, ldap.SCOPE_SUBTREE, "(uid=%(user)s)")
        AUTH_LDAP_USER_QUERY_FIELD = 'email'
        
        group_search_dn = os.getenv('AUTH_LDAP_GROUP_SEARCH_DN', 'cn=groups,cn=accounts,dc=your,dc=domain,dc=ru')
        AUTH_LDAP_GROUP_SEARCH = LDAPSearch(group_search_dn, ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)")
        AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")
        
        AUTH_LDAP_REQUIRE_GROUP = os.getenv('AUTH_LDAP_REQUIRE_GROUP', '')
        
        AUTH_LDAP_USER_ATTR_MAP = {
            "first_name": "givenName",
            "last_name": "sn",
            "email": "mail",
            "username": "mail",
        }
        AUTH_LDAP_ALWAYS_UPDATE_USER = False
        AUTH_LDAP_NO_NEW_USERS = False
    except ImportError as exc:
        # Раньше ошибка проглатывалась и приложение тихо откатывалось на
        # локальную авторизацию — пользователи просто не могли войти.
        raise ImproperlyConfigured(
            "USE_LDAP=True, но зависимости LDAP не установлены. "
            "Раскомментируйте django-auth-ldap в requirements.txt и переустановите зависимости."
        ) from exc

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'users',
    'data',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Раздаёт собранную статику под Gunicorn без отдельного веб-сервера.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.youtrack_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'my_project_db'),
        'USER': os.getenv('DB_USER', 'my_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'my_password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True

YOUTRACK_BASE_URL = os.getenv('YOUTRACK_BASE_URL', 'https://youtrack.company.com').rstrip('/')

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'core.storage.ResilientManifestStaticFilesStorage'},
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Ограничения загрузки файлов.
# MAX_ATTACHMENT_SIZE проверяется в data.validators, два параметра ниже —
# защита самого Django от разрастания тела запроса.
MAX_ATTACHMENT_SIZE = int(os.getenv('MAX_ATTACHMENT_SIZE', 25 * 1024 * 1024))
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_ATTACHMENT_SIZE + 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000

# Браузер не должен угадывать тип пользовательского файла по содержимому.
SECURE_CONTENT_TYPE_NOSNIFF = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_django': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_app': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_django'],
            'level': 'ERROR',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
        'data': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
        'notifications': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
        'django_auth_ldap': {
            'handlers': ['console', 'file_app'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}