"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
from pathlib import Path

# Settings LDAP

# LDAP_CA_FILE = "path/for/your/crt"
# ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, LDAP_CA_FILE)
# ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
# ldap.set_option(ldap.OPT_X_TLS_NEWCTX, 0)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+*60&(+f438kalqo-4ku@meb@+$i4*u&b*t*vxt1@880#=+40$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

AUTH_USER_MODEL = 'users.User'

SESSION_COOKIE_AGE = 1209600

# Authentication LDAP

# AUTHENTICATION_BACKENDS = [
#     "django_auth_ldap.backend.LDAPBackend",
#     "django.contrib.auth.backends.ModelBackend",
# ]

# AUTH_LDAP_SERVER_URI = "ldap://your.domain.ru"
# AUTH_LDAP_START_TLS = True

# AUTH_LDAP_BIND_DN = (
#     "uid=django_service,cn=sysaccounts,cn=etc,"
#     "dc=your,dc=domain,dc=ru"
# )

# AUTH_LDAP_BIND_PASSWORD = "your_password"

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "cn=users,cn=accounts,dc=your,dc=domain,dc=ru",
#     ldap.SCOPE_SUBTREE,
#     "(uid=%(user)s)",
# )

# AUTH_LDAP_USER_QUERY_FIELD = 'email'

# AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
#     "cn=groups,cn=accounts,dc=your,dc=domain,dc=ru",
#     ldap.SCOPE_SUBTREE,
#     "(objectClass=groupOfNames)",
# )

# AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")

# AUTH_LDAP_REQUIRE_GROUP = (
#     "cn=django-users,cn=groups,cn=accounts,"
#     "dc=your,dc=domain,dc=ru"
# )

# AUTH_LDAP_USER_ATTR_MAP = {
#     "first_name": "givenName",
#     "last_name": "sn",
#     "email": "mail",
#     "username": "mail",
# }

# AUTH_LDAP_ALWAYS_UPDATE_USER = False
# AUTH_LDAP_NO_NEW_USERS = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_apscheduler',
    'users',
    'data',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.ValidateUserActiveMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'my_project_db',      
        'USER': 'my_user',            
        'PASSWORD': 'my_password',    
        'HOST': 'localhost',          
        'PORT': '5432',               
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'