# Generated by Django 6.0.6 on 2026-09-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mattermostsetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Настройка Mattermost', 'verbose_name_plural': 'Настройки Mattermost'},
        ),
    ]
